### PR TITLE
MockFirestoreInstance to remember saved documents

### LINKED ISSUE #20: collection('...').document() should not save a document
With current implementation, the following test code fails:
```
    final reference1 = firestore.collection('users').document();
    final reference2 = firestore.collection('users').document();

    await reference1.setData({
      'someField': 'someValue',
    });

    QuerySnapshot querySnapshot = await firestore.collection('users').getDocuments();
    // Only reference1 is saved
    expect(querySnapshot.documents, hasLength(1));
    expect(querySnapshot.documents.first['someField'], 'someValue');
```

It fails because as of now cloud_firestore_mocks does not distinguish saved and unsaved documents.

I suspect code below should be updated to accommodate this.
```
  @override
  DocumentReference document([String path]) {
    if (path == null) {
      path = _generateAutoId();
    }

    return MockDocumentReference(path, getSubpath(root, path), root,
        getSubpath(snapshotStreamControllerRoot, path));
  }
```

`getSubpath(root, path)` creates a document to the root.

### PR DESCRIPTION
**Pull request by suztomo**
Fixes #20 and #21 .

### CODE REVIEW

**Comment by suztomo** [comment]
Will resolve conflict.

File: test/cloud_firestore_mocks_test.dart [hunk 1]
```diff
@@ -140,6 +140,84 @@ void main() {
...
+    expect(documentReference.path, 'users/aaa/friends/bbb/friends-friends/ccc');
+  });
+
+  test('Creating document reference should not save the document', () async {
+    final instance = MockFirestoreInstance();
+    await instance.collection('users').add(<String, dynamic>{'name': 'Foo'});
+    final documentReference = instance.collection('users').document(uid);
+
+    var querySnapshot = await instance.collection('users').getDocuments();
+    expect(querySnapshot.documents, hasLength(1));
```
Comment (suztomo) [inline test/cloud_firestore_mocks_test.dart]: This is the very motivation of this PR.

File: lib/src/cloud_firestore_mocks_base.dart [hunk 2]
```diff
@@ -40,6 +44,18 @@ class MockFirestoreInstance extends Mock implements Firestore {
     return jsonText;
   }
 
+  void saveDocument(String path) {
```
Comment (atn832) [inline lib/src/cloud_firestore_mocks_base.dart]: Consider moving all the saveDocument functionality to a class that is not exposed, so that it doesn't show up in the documentation.

Comment (atn832) [reply lib/src/cloud_firestore_mocks_base.dart]: I've filed #36 to keep track of it.

**Comment by atn832** [comment]
Published this, along with your other PRs to https://pub.dev/packages/cloud_firestore_mocks#041. Thank you as always!

**Comment by suztomo** [comment]
@atn832 Thank you.
